<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>Withings.NET</PackageId>
    <Authors>Withings.NET Contributors</Authors>
    <Company />
    <Product>Withings.NET</Product>
  </PropertyGroup>


</Project>
