<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageId>Withings.NET</PackageId>
    <Authors>Withings.NET Contributors</Authors>
    <Company />
    <Product>Withings.NET</Product>
  </PropertyGroup>


</Project>
