services:
  tests:
    build: .
    command: dotnet test Withings.NET.sln --no-build --verbosity normal --filter "TestCategory!=E2E"

  web:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    working_dir: /app/Withings.Example
    command: dotnet run --project Withings.Example.csproj
